name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12.x', '14.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Set docker context
        run: export DOCKER_HOST=$(docker context inspect --format '{{.Endpoints.docker.Host}}')

      - name: Start containers
        run: docker-compose -f "docker-compose.yaml" up -d --build

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm lint

      - name: Test
        run: npm test --ci --coverage --maxWorkers=2

      - name: Build
        run: npm build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yaml" down